SELECT F.FLAVOR
FROM FIRST_HALF F
    INNER JOIN(
        SELECT FLAVOR
        FROM ICECREAM_INFO
        WHERE INGREDIENT_TYPE='fruit_based'        
    ) I
    ON F.FLAVOR=I.FLAVOR
    WHERE TOTAL_ORDER>3000
    ORDER BY TOTAL_ORDER DESC;