SELECT B.TITLE, B.BOARD_ID, U.REPLY_ID, U.WRITER_ID, U.CONTENTS, U.CREATED_DATE
FROM USED_GOODS_REPLY U
LEFT JOIN USED_GOODS_BOARD B
ON U.BOARD_ID=B.BOARD_ID
WHERE YEAR(B.CREATED_DATE)='2022' AND MONTH(B.CREATED_DATE)='10'
ORDER BY U.CREATED_DATE ASC, B.TITLE;